export const LOGIN_API_CALL = 'Login-API-Call'
export const LOGIN_API_RESPONSE = 'Login-API-Response'
export const REGISTER_API_CALL = 'Register-Api-Call'
export const REGISTER_API_RESPONSE = 'Register-Api-Response'
export const ERROR_TYPE = 'ERROR'
export const ERROR_MESSAGE = 'ERROR-MESSAGE'
export const CLEAR_ERROR_MESSAGE = 'CLEAR-ERROR-MESSAGE'